/**
 * Loads the Emscripten module under Node. The shipped build targets
 * web/worker only, so the wasm binary is handed over directly instead of
 * going through fetch().
 */
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

// @ts-ignore generated by `npm run build:wasm`
import createSeedForge from '../src/wasm/seedforge.js';

const WASM = fileURLToPath(new URL('../src/wasm/seedforge.wasm', import.meta.url));

export async function loadModule(): Promise<any> {
  const binary = await readFile(WASM);
  return createSeedForge({
    instantiateWasm(imports: WebAssembly.Imports, cb: (inst: WebAssembly.Instance) => void) {
      const mod = new WebAssembly.Module(binary);
      cb(new WebAssembly.Instance(mod, imports));
      return {};
    },
  });
}
