/**
 * Thin typed wrapper around the Emscripten module produced by wasm/build.sh.
 *
 * Owns the scratch buffers in WASM memory so a running search does not
 * allocate per block.
 */

// @ts-ignore generated by `npm run build:wasm` - not checked into git
import createSeedForge from '../wasm/seedforge.js';

import { CRIT_INTS, PAIR_INTS, encodeCriteria, encodeRules } from './criteria';
import type { Criterion, Edition, Match, MatchHit, ProximityRule, TargetMode } from './types';

interface EmscriptenModule {
  HEAP32: Int32Array;
  HEAPU8: Uint8Array;
  _malloc(bytes: number): number;
  _free(ptr: number): void;
  _sf_configure(mc: number, edition: number, target: number, crit: number, ncrit: number, pairs: number, npairs: number): number;
  _sf_run(start: bigint, count: number, seeds: number, data: number, spawn: number, maxOut: number): number;
  _sf_supported(type: number, mc: number): number;
  _sf_region_size(type: number, mc: number): number;
  _sf_mc_newest(): number;
  _sf_max_crit(): number;
  _sf_crit_ints(): number;
  _sf_pair_ints(): number;
  _sf_max_pairs(): number;
  _sf_biome_supported(biome: number, mc: number): number;
  _sf_bedrock_supported(type: number): number;
  _sf_stat_scanned(): number;
  _sf_stat_stage2(): number;
  _sf_spawn(seed: bigint, mc: number, exact: number, out: number): number;
}

const MAX_OUT = 64;

export class SearchEngine {
  private constructor(
    private readonly m: EmscriptenModule,
    private readonly maxCrit: number,
    private readonly critPtr: number,
    private readonly pairPtr: number,
    private readonly seedsPtr: number,
    private readonly dataPtr: number,
    private readonly spawnPtr: number,
  ) {}

  static async create(): Promise<SearchEngine> {
    const m = (await createSeedForge()) as EmscriptenModule;
    const maxCrit = m._sf_max_crit();
    if (m._sf_crit_ints() !== CRIT_INTS) {
      throw new Error('WASM core is out of date - re-run `npm run build:wasm`.');
    }
    return new SearchEngine(
      m,
      maxCrit,
      m._malloc(maxCrit * CRIT_INTS * 4),
      m._malloc(m._sf_max_pairs() * PAIR_INTS * 4),
      m._malloc(MAX_OUT * 8),
      m._malloc(MAX_OUT * maxCrit * 4 * 4),
      m._malloc(MAX_OUT * 2 * 4),
    );
  }

  /** Whether a structure type exists in a given Minecraft version. */
  supports(structure: number, mc: number): boolean {
    return this.m._sf_supported(structure, mc) !== 0;
  }

  /** Whether a biome generates in the overworld of a given Minecraft version. */
  supportsBiome(biome: number, mc: number): boolean {
    return this.m._sf_biome_supported(biome, mc) !== 0;
  }

  /** Whether the Bedrock generator places this structure at all. */
  supportsBedrock(structure: number): boolean {
    return this.m._sf_bedrock_supported(structure) !== 0;
  }

  /**
   * Installs the search criteria. Throws when a structure does not exist in
   * the selected version, or when too many criteria were given.
   */
  configure(
    mc: number,
    edition: Edition,
    target: TargetMode,
    criteria: readonly Criterion[],
    rules: readonly ProximityRule[] = [],
  ): void {
    if (criteria.length === 0) throw new Error('Pick at least one structure.');
    if (criteria.length > this.maxCrit) {
      throw new Error(`At most ${this.maxCrit} structures can be combined.`);
    }
    if (rules.length > this.m._sf_max_pairs()) {
      throw new Error(`At most ${this.m._sf_max_pairs()} proximity rules are supported.`);
    }
    this.m.HEAP32.set(encodeCriteria(criteria), this.critPtr >> 2);
    this.m.HEAP32.set(encodeRules(rules), this.pairPtr >> 2);
    const rc = this.m._sf_configure(
      mc, edition, target, this.critPtr, criteria.length, this.pairPtr, rules.length,
    );
    if (rc < 0) {
      const messages: Record<number, string> = {
        [-3]: 'One of the selected structures does not exist in this Minecraft version.',
        [-4]: 'One of the selected biomes does not exist in this Minecraft version.',
        [-5]:
          'That radius is too large for a biome search. Reduce it, or drop the biome criteria.',
        [-6]: 'Ran out of memory setting up the biome search.',
        [-7]: 'A proximity rule refers to a structure that is not selected.',
        [-8]:
          'A proximity rule reaches into the End, which has no coordinate link to the Overworld or the Nether.',
        [-9]:
          'Bedrock searching needs 1.18 or later - that is when the two editions were unified onto the same world generator.',
        [-10]: 'One of the selected structures is not placed by the Bedrock generator.',
        [-11]:
          'That variant filter only works on Java. Bedrock rolls structure variants with a different generator, so the answer would not describe your world.',
        [-12]:
          'The combined nether criterion is for Bedrock only. On Java, search for a fortress or a bastion directly.',
      };
      throw new Error(messages[rc] ?? `Search could not be configured (code ${rc}).`);
    }
  }

  /** Scans `count` consecutive seeds starting at `start`. */
  run(start: bigint, count: number, criteria: readonly Criterion[]): { matches: Match[]; scanned: number; stage2: number } {
    const n = this.m._sf_run(
      BigInt.asUintN(64, start),
      count,
      this.seedsPtr,
      this.dataPtr,
      this.spawnPtr,
      MAX_OUT,
    );
    const seeds = new BigUint64Array(this.m.HEAPU8.buffer, this.seedsPtr, MAX_OUT);
    const matches: Match[] = [];
    for (let i = 0; i < n; i++) {
      const hits: MatchHit[] = [];
      for (let k = 0; k < criteria.length; k++) {
        const b = (this.dataPtr >> 2) + (i * this.maxCrit + k) * 4;
        hits.push({
          kind: criteria[k]!.kind,
          id: criteria[k]!.id,
          x: this.m.HEAP32[b]!,
          z: this.m.HEAP32[b + 1]!,
          biome: this.m.HEAP32[b + 2]!,
          dim: this.m.HEAP32[b + 3]!,
        });
      }
      matches.push({
        seed: seeds[i]!,
        spawnX: this.m.HEAP32[(this.spawnPtr >> 2) + i * 2]!,
        spawnZ: this.m.HEAP32[(this.spawnPtr >> 2) + i * 2 + 1]!,
        hits,
      });
    }
    return {
      matches,
      scanned: this.m._sf_stat_scanned(),
      stage2: this.m._sf_stat_stage2(),
    };
  }

  /**
   * Looks at one specific seed rather than searching for seeds.
   *
   * Runs the same criteria against a single seed and reports what it finds,
   * so a seed can be checked instead of hunted for. Returns null when the
   * seed does not satisfy everything asked of it.
   */
  inspect(
    seed: bigint,
    mc: number,
    edition: Edition,
    target: TargetMode,
    criteria: readonly Criterion[],
    rules: readonly ProximityRule[] = [],
  ): Match | null {
    this.configure(mc, edition, target, criteria, rules);
    const { matches } = this.run(seed, 1, criteria);
    return matches[0] ?? null;
  }

  /** Largest number of matches a single `run()` call can return. */
  get maxOut(): number {
    return MAX_OUT;
  }
}
