/**
 * Thin typed wrapper around the Emscripten module produced by wasm/build.sh.
 *
 * Owns the scratch buffers in WASM memory so a running search does not
 * allocate per block.
 */

// @ts-ignore generated by `npm run build:wasm` - not checked into git
import createSeedForge from '../wasm/seedforge.js';

import { CRIT_INTS, encodeCriteria } from './criteria';
import type { Criterion, Match, MatchHit, TargetMode } from './types';

interface EmscriptenModule {
  HEAP32: Int32Array;
  HEAPU8: Uint8Array;
  _malloc(bytes: number): number;
  _free(ptr: number): void;
  _sf_configure(mc: number, radius: number, target: number, crit: number, ncrit: number): number;
  _sf_run(start: bigint, count: number, seeds: number, data: number, spawn: number, maxOut: number): number;
  _sf_supported(type: number, mc: number): number;
  _sf_region_size(type: number, mc: number): number;
  _sf_mc_newest(): number;
  _sf_max_crit(): number;
  _sf_crit_ints(): number;
  _sf_stat_scanned(): number;
  _sf_stat_stage2(): number;
  _sf_spawn(seed: bigint, mc: number, exact: number, out: number): number;
}

const MAX_OUT = 64;

export class SearchEngine {
  private constructor(
    private readonly m: EmscriptenModule,
    private readonly maxCrit: number,
    private readonly critPtr: number,
    private readonly seedsPtr: number,
    private readonly dataPtr: number,
    private readonly spawnPtr: number,
  ) {}

  static async create(): Promise<SearchEngine> {
    const m = (await createSeedForge()) as EmscriptenModule;
    const maxCrit = m._sf_max_crit();
    if (m._sf_crit_ints() !== CRIT_INTS) {
      throw new Error('WASM core is out of date - re-run `npm run build:wasm`.');
    }
    return new SearchEngine(
      m,
      maxCrit,
      m._malloc(maxCrit * CRIT_INTS * 4),
      m._malloc(MAX_OUT * 8),
      m._malloc(MAX_OUT * maxCrit * 4 * 4),
      m._malloc(MAX_OUT * 2 * 4),
    );
  }

  /** Newest Minecraft version cubiomes knows about. */
  newestVersion(): number {
    return this.m._sf_mc_newest();
  }

  /** Whether a structure type exists in a given Minecraft version. */
  supports(structure: number, mc: number): boolean {
    return this.m._sf_supported(structure, mc) !== 0;
  }

  /** Region grid size, in chunks, for a structure type. */
  regionSize(structure: number, mc: number): number {
    return this.m._sf_region_size(structure, mc);
  }

  /** World spawn of a single seed, estimated or exact. */
  spawn(seed: bigint, mc: number, exact: boolean): { x: number; z: number } {
    const ptr = this.spawnPtr;
    this.m._sf_spawn(BigInt.asUintN(64, seed), mc, exact ? 1 : 0, ptr);
    return { x: this.m.HEAP32[ptr >> 2]!, z: this.m.HEAP32[(ptr >> 2) + 1]! };
  }

  /**
   * Installs the search criteria. Throws when a structure does not exist in
   * the selected version, or when too many criteria were given.
   */
  configure(mc: number, radius: number, target: TargetMode, criteria: readonly Criterion[]): void {
    if (criteria.length === 0) throw new Error('Pick at least one structure.');
    if (criteria.length > this.maxCrit) {
      throw new Error(`At most ${this.maxCrit} structures can be combined.`);
    }
    const enc = encodeCriteria(criteria);
    this.m.HEAP32.set(enc, this.critPtr >> 2);
    const rc = this.m._sf_configure(mc, radius, target, this.critPtr, criteria.length);
    if (rc < 0) {
      throw new Error(
        rc === -3
          ? 'One of the selected structures does not exist in this Minecraft version.'
          : `Search could not be configured (code ${rc}).`,
      );
    }
  }

  /** Scans `count` consecutive seeds starting at `start`. */
  run(start: bigint, count: number, criteria: readonly Criterion[]): { matches: Match[]; scanned: number; stage2: number } {
    const n = this.m._sf_run(
      BigInt.asUintN(64, start),
      count,
      this.seedsPtr,
      this.dataPtr,
      this.spawnPtr,
      MAX_OUT,
    );
    const seeds = new BigUint64Array(this.m.HEAPU8.buffer, this.seedsPtr, MAX_OUT);
    const matches: Match[] = [];
    for (let i = 0; i < n; i++) {
      const hits: MatchHit[] = [];
      for (let k = 0; k < criteria.length; k++) {
        const b = (this.dataPtr >> 2) + (i * this.maxCrit + k) * 4;
        hits.push({
          structure: criteria[k]!.structure,
          x: this.m.HEAP32[b]!,
          z: this.m.HEAP32[b + 1]!,
          biome: this.m.HEAP32[b + 2]!,
          dim: this.m.HEAP32[b + 3]!,
        });
      }
      matches.push({
        seed: seeds[i]!,
        spawnX: this.m.HEAP32[(this.spawnPtr >> 2) + i * 2]!,
        spawnZ: this.m.HEAP32[(this.spawnPtr >> 2) + i * 2 + 1]!,
        hits,
      });
    }
    return {
      matches,
      scanned: this.m._sf_stat_scanned(),
      stage2: this.m._sf_stat_stage2(),
    };
  }

  /** Largest number of matches a single `run()` call can return. */
  get maxOut(): number {
    return MAX_OUT;
  }
}
